// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYAMrUg48sVEeyJiPTIXEjqXrKx0MAs8',
    appId: '1:366708418720:web:a1385a89d1d1c61710c1c5',
    messagingSenderId: '366708418720',
    projectId: 'crud-firebase-app-2b632',
    authDomain: 'crud-firebase-app-2b632.firebaseapp.com',
    storageBucket: 'crud-firebase-app-2b632.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7C65lZS9fmp3MXfyGjMUVUPCHMgLrXc',
    appId: '1:366708418720:android:f79d13efe30ed85710c1c5',
    messagingSenderId: '366708418720',
    projectId: 'crud-firebase-app-2b632',
    storageBucket: 'crud-firebase-app-2b632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZXOBZfiVYOFTkaQQ_0Vh851esBbahNY',
    appId: '1:366708418720:ios:982d0ffe0700cfd310c1c5',
    messagingSenderId: '366708418720',
    projectId: 'crud-firebase-app-2b632',
    storageBucket: 'crud-firebase-app-2b632.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZXOBZfiVYOFTkaQQ_0Vh851esBbahNY',
    appId: '1:366708418720:ios:982d0ffe0700cfd310c1c5',
    messagingSenderId: '366708418720',
    projectId: 'crud-firebase-app-2b632',
    storageBucket: 'crud-firebase-app-2b632.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdYAMrUg48sVEeyJiPTIXEjqXrKx0MAs8',
    appId: '1:366708418720:web:2af708557272c14a10c1c5',
    messagingSenderId: '366708418720',
    projectId: 'crud-firebase-app-2b632',
    authDomain: 'crud-firebase-app-2b632.firebaseapp.com',
    storageBucket: 'crud-firebase-app-2b632.firebasestorage.app',
  );
}
