// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zyOT7-nsQEUeQtyxlFBn69lZD8Py5mg',
    appId: '1:120742289617:web:254cce824c17f3224a25f0',
    messagingSenderId: '120742289617',
    projectId: 'project-firebase-f9b3a',
    authDomain: 'project-firebase-f9b3a.firebaseapp.com',
    storageBucket: 'project-firebase-f9b3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOucw5_CQcT7lifCvGkTZstpNoup7G5E',
    appId: '1:120742289617:android:1496f6961208de874a25f0',
    messagingSenderId: '120742289617',
    projectId: 'project-firebase-f9b3a',
    storageBucket: 'project-firebase-f9b3a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2oqXOFgIMs7G8Vn1L5to-Yjrv3hrwu0s',
    appId: '1:120742289617:ios:1955fea61b0d9c384a25f0',
    messagingSenderId: '120742289617',
    projectId: 'project-firebase-f9b3a',
    storageBucket: 'project-firebase-f9b3a.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2oqXOFgIMs7G8Vn1L5to-Yjrv3hrwu0s',
    appId: '1:120742289617:ios:1955fea61b0d9c384a25f0',
    messagingSenderId: '120742289617',
    projectId: 'project-firebase-f9b3a',
    storageBucket: 'project-firebase-f9b3a.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zyOT7-nsQEUeQtyxlFBn69lZD8Py5mg',
    appId: '1:120742289617:web:019e70f02bbc0a214a25f0',
    messagingSenderId: '120742289617',
    projectId: 'project-firebase-f9b3a',
    authDomain: 'project-firebase-f9b3a.firebaseapp.com',
    storageBucket: 'project-firebase-f9b3a.firebasestorage.app',
  );

}